# Generated by Django 4.0.3 on 2022-04-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login1',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='login1',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.register1'),
        ),
        migrations.AlterField(
            model_name='register1',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
