# Generated by Django 4.0.3 on 2022-05-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='pancard',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='pancard_image',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='Coupon_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='profile_image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
