# Generated by Django 4.0.3 on 2022-05-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_custom_user_pancard_custom_user_pancard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='emission_test_image',
            field=models.FileField(null=True, upload_to='images/Emission_image'),
        ),
        migrations.AddField(
            model_name='driver',
            name='fitness_certificate_image',
            field=models.FileField(null=True, upload_to='images/Fitness_certificate_image'),
        ),
        migrations.AddField(
            model_name='driver',
            name='insurence_image',
            field=models.FileField(null=True, upload_to='images/Insurence_image'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_image',
            field=models.FileField(null=True, upload_to='images/License_image'),
        ),
        migrations.AddField(
            model_name='driver',
            name='permit_expire_image',
            field=models.FileField(null=True, upload_to='images/Permit_image'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rc_image',
            field=models.FileField(null=True, upload_to='images/Rc_image'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='pancard_image',
            field=models.FileField(null=True, upload_to='images/Pancard_image'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='profile_image',
            field=models.FileField(null=True, upload_to='images/Profile_image'),
        ),
    ]
