# Generated by Django 4.0.5 on 2022-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driver_emission_test_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup_details',
            name='pickup_time',
            field=models.TimeField(max_length=10),
        ),
    ]
