# Generated by Django 4.0.3 on 2022-05-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_forgotpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpassword',
            old_name='email',
            new_name='username',
        ),
    ]
