# Generated by Django 4.0.5 on 2022-06-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pickup_details_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='pancard_image',
            field=models.ImageField(null=True, upload_to='images/Pancard_image'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/Profile_image'),
        ),
    ]
