# Generated by Django 4.0.3 on 2022-05-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
