# Generated by Django 4.0.3 on 2022-05-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register1',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='register1',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
