# Generated by Django 4.0.3 on 2022-05-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_firstname_register1_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='django_user',
        ),
        migrations.AlterField(
            model_name='login1',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
