# Generated by Django 4.0.3 on 2022-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_vehicle_badge_vehicle_max_time_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('mobile_number', models.IntegerField(null=True)),
            ],
        ),
    ]
