# Generated by Django 4.0.3 on 2022-05-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_account_details_custom_user_customer_address_driver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login1',
            old_name='username',
            new_name='email',
        ),
    ]
