# Generated by Django 4.0.3 on 2022-05-26 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_username_login1_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register1',
            name='confirm_password',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
