# Generated by Django 4.0.3 on 2022-05-26 10:32

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_register1_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpassword',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='resetpassword',
            old_name='username',
            new_name='email',
        ),
        migrations.AddField(
            model_name='resetpassword',
            name='password',
            field=models.CharField(max_length=128, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
