# Generated by Django 4.0.3 on 2022-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_username_forgotpassword_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='max_time_min',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='min_charge',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='price_per_km',
            field=models.FloatField(max_length=100),
        ),
    ]
