# Generated by Django 4.0.3 on 2022-06-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_vehicletype_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleTypeName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicletype')),
            ],
        ),
    ]
