# Generated by Django 4.0.3 on 2022-06-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_filtervehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
