# Generated by Django 4.0.3 on 2022-06-28 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{4}(\\ )[a-zA-Z]*$', 'Only Letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='register1',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_plan_name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Gold', 'Gold'), ('Premium', 'Premium')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='User_Role_Name',
            field=models.CharField(choices=[('User', 'User'), ('Owner', 'Owner'), ('Driver', 'Driver')], max_length=100),
        ),
    ]
