# Generated by Django 4.0.3 on 2022-07-04 08:29

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='Vehicle_number',
            field=models.CharField(max_length=100, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
